# Generated by Django 4.2.1 on 2023-09-17 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeopleAlsoBuy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_also', models.ManyToManyField(related_name='bu_also', to='Products.sextoys')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='people_buy_also', to='Products.sextoys')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('all_product', models.ManyToManyField(related_name='carts', to='Products.sextoys')),
            ],
        ),
    ]
