# Generated by Django 4.2.1 on 2023-09-15 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0003_alter_productfeature_product_feature_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeopleBuyAlso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_also', models.ManyToManyField(to='Products.sextoys')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_buy', to='Products.sextoys')),
            ],
        ),
    ]
