# Generated by Django 4.2.1 on 2023-06-23 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_name', models.CharField(max_length=50)),
                ('color_rgb', models.CharField(max_length=10)),
                ('slug', models.SlugField(unique=True)),
                ('status', models.CharField(choices=[('published', 'PUBLISHED'), ('unpublished', 'UNPUBLISHED')], default='published', max_length=20)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
                ('page_title', models.CharField(default='جی جی کالا', max_length=30)),
                ('slug', models.SlugField(unique=True)),
                ('status', models.BooleanField(default=True)),
                ('caption', models.TextField(default='')),
                ('photo', models.ImageField(blank=True, upload_to='Category-photo')),
                ('parent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parents_related', to='Category.category')),
            ],
            options={
                'ordering': ['parent__id', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=100)),
                ('page_title', models.CharField(default='جی جی کالا', max_length=30)),
                ('slug', models.SlugField(unique=True)),
                ('status', models.BooleanField(default=True)),
                ('caption', models.TextField(default='')),
                ('photo', models.ImageField(blank=True, upload_to='Brand-photo')),
                ('parent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brand_related', to='Category.brand')),
            ],
            options={
                'ordering': ['parent__id', 'id'],
            },
        ),
    ]
